version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: product-catalog-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: product-catalog-db
      ME_CONFIG_MONGODB_PORT: 27017

volumes:
  mongodb-data:
