version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: product-catalog-db
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: product-catalog-db
      ME_CONFIG_MONGODB_PORT: 27017

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml

  product-catalog:
    build: .
    container_name: product-catalog
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb
      MONGO_PORT: 27017

volumes:
  mongodb-data:
